#define INCLUDE                          1
#define DQSTR                            2
#define LINEBREAK                        3
#define CHEADER                          4
#define IMPORT                           5
#define NAMESPACE                        6
#define IDENTIFIER                       7
#define COLON                            8
#define INDENT                           9
#define DEDENT                          10
#define DLNAME                          11
#define ENUM                            12
#define PDEF                            13
#define OPENPAREN                       14
#define CLOSEPAREN                      15
#define COMMA                           16
#define EQ                              17
#define DIGITS                          18
#define CLASS                           19
#define UNION                           20
#define DEF                             21
#define ITERATOR                        22
#define FOR                             23
#define IN                              24
#define STATIC                          25
#define MEMBER                          26
#define OPENSQRPAREN                    27
#define CLOSESQRPAREN                   28
#define OUT                             29
#define NOREF                           30
#define NO_PYTHON                       31
#define INT                             32
#define UINT                            33
#define FLOAT                           34
#define STRING                          35
#define CHAR                            36
#define PVOID                           37
#define BOOL                            38
#define SET                             39
#define BIT                             40
