/* Generated by re2c 0.13.5 on Thu Mar 20 19:29:42 2014 */
#line 1 "zidl.l"
/*

	ZIDL lexer for re2c lexer generator

*/

#define YYCTYPE char
#define YYCURSOR s->cursor()
#define YYLIMIT s->limit()
#define YYMARKER q
#define YYFILL(n) s->fill(n)

int scan(scanner* s) {
	int depth;
	char* q;

	if (s->bufferline == s->cursor()) goto indent;

ignoretoken:
	s->token = s->cursor();


#line 26 "zidl_l.h"
{
	YYCTYPE yych;
	unsigned int yyaccept = 0;

	if ((YYLIMIT - YYCURSOR) < 10) YYFILL(10);
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy41;
	case '\t':
	case ' ':	goto yy37;
	case '\n':	goto yy33;
	case '\r':	goto yy35;
	case '"':	goto yy29;
	case '#':	goto yy39;
	case '(':	goto yy17;
	case ')':	goto yy19;
	case ',':	goto yy25;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy31;
	case ':':	goto yy15;
	case '=':	goto yy27;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'g':
	case 'h':
	case 'j':
	case 'k':
	case 'l':
	case 'q':
	case 'r':
	case 't':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	case '[':	goto yy21;
	case ']':	goto yy23;
	case 'b':	goto yy10;
	case 'c':	goto yy2;
	case 'd':	goto yy14;
	case 'e':	goto yy6;
	case 'f':	goto yy12;
	case 'i':	goto yy4;
	case 'm':	goto yy8;
	case 'n':	goto yy5;
	case 'o':	goto yy13;
	case 'p':	goto yy11;
	case 's':	goto yy9;
	case 'u':	goto yy7;
	default:	goto yy43;
	}
yy2:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'h':	goto yy176;
	case 'l':	goto yy177;
	default:	goto yy49;
	}
yy3:
#line 81 "zidl.l"
	{ return IDENTIFIER; }
#line 123 "zidl_l.h"
yy4:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy152;
	case 'n':	goto yy153;
	case 't':	goto yy155;
	default:	goto yy49;
	}
yy5:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy130;
	case 'o':	goto yy131;
	default:	goto yy49;
	}
yy6:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy126;
	default:	goto yy49;
	}
yy7:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy117;
	case 'n':	goto yy118;
	default:	goto yy49;
	}
yy8:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy111;
	default:	goto yy49;
	}
yy9:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy97;
	case 't':	goto yy98;
	default:	goto yy49;
	}
yy10:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy90;
	case 'o':	goto yy91;
	default:	goto yy49;
	}
yy11:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy81;
	case 'v':	goto yy82;
	default:	goto yy49;
	}
yy12:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy73;
	case 'o':	goto yy74;
	default:	goto yy49;
	}
yy13:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy70;
	default:	goto yy49;
	}
yy14:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy61;
	case 'l':	goto yy62;
	default:	goto yy49;
	}
yy15:
	++YYCURSOR;
#line 64 "zidl.l"
	{ return COLON; }
#line 203 "zidl_l.h"
yy17:
	++YYCURSOR;
#line 65 "zidl.l"
	{ return OPENPAREN; }
#line 208 "zidl_l.h"
yy19:
	++YYCURSOR;
#line 66 "zidl.l"
	{ return CLOSEPAREN; }
#line 213 "zidl_l.h"
yy21:
	++YYCURSOR;
#line 67 "zidl.l"
	{ return OPENSQRPAREN; }
#line 218 "zidl_l.h"
yy23:
	++YYCURSOR;
#line 68 "zidl.l"
	{ return CLOSESQRPAREN; }
#line 223 "zidl_l.h"
yy25:
	++YYCURSOR;
#line 69 "zidl.l"
	{ return COMMA; }
#line 228 "zidl_l.h"
yy27:
	++YYCURSOR;
#line 70 "zidl.l"
	{ return EQ; }
#line 233 "zidl_l.h"
yy29:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 0x00:
	case '\n':	goto yy30;
	default:	goto yy54;
	}
yy30:
#line 85 "zidl.l"
	{ return -1; }
#line 245 "zidl_l.h"
yy31:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy52;
yy32:
#line 72 "zidl.l"
	{ return DIGITS; }
#line 253 "zidl_l.h"
yy33:
	++YYCURSOR;
yy34:
#line 73 "zidl.l"
	{ 
	s->bufferline = s->cursor(); 
	s->linecounter++;
	if (s->linetokens == 0) 
		goto indent;
	s->linetokens = 0; 
	return LINEBREAK; 
}
#line 266 "zidl_l.h"
yy35:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy50;
	default:	goto yy30;
	}
yy36:
	yych = *++YYCURSOR;
	goto yy49;
yy37:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy47;
yy38:
#line 82 "zidl.l"
	{ goto ignoretoken; }
#line 283 "zidl_l.h"
yy39:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy45;
yy40:
#line 83 "zidl.l"
	{ goto ignoretoken; }
#line 291 "zidl_l.h"
yy41:
	++YYCURSOR;
#line 84 "zidl.l"
	{ goto indent; }
#line 296 "zidl_l.h"
yy43:
	yych = *++YYCURSOR;
	goto yy30;
yy44:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy45:
	switch (yych) {
	case 0x00:
	case '\n':
	case '\r':	goto yy40;
	default:	goto yy44;
	}
yy46:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy47:
	switch (yych) {
	case '\t':
	case ' ':	goto yy46;
	default:	goto yy38;
	}
yy48:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy49:
	switch (yych) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy48;
	default:	goto yy3;
	}
yy50:
	yych = *++YYCURSOR;
	goto yy34;
yy51:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy52:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy51;
	default:	goto yy32;
	}
yy53:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy54:
	switch (yych) {
	case 0x00:
	case '\n':	goto yy55;
	case '"':	goto yy58;
	case '\\':	goto yy56;
	default:	goto yy53;
	}
yy55:
	YYCURSOR = YYMARKER;
	switch (yyaccept) {
	case 0: 	goto yy30;
	case 1: 	goto yy59;
	}
yy56:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:
	case '\n':	goto yy55;
	case '"':	goto yy60;
	case '\\':	goto yy56;
	default:	goto yy53;
	}
yy58:
	++YYCURSOR;
yy59:
#line 71 "zidl.l"
	{ return DQSTR; }
#line 448 "zidl_l.h"
yy60:
	yyaccept = 1;
	YYMARKER = ++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:
	case '\n':	goto yy59;
	case '"':	goto yy58;
	case '\\':	goto yy56;
	default:	goto yy53;
	}
yy61:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'f':	goto yy68;
	default:	goto yy49;
	}
yy62:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy63;
	default:	goto yy49;
	}
yy63:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy64;
	default:	goto yy49;
	}
yy64:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy65;
	default:	goto yy49;
	}
yy65:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy66;
	default:	goto yy49;
	}
yy66:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy48;
	default:	goto yy67;
	}
yy67:
#line 63 "zidl.l"
	{ return DLNAME; }
#line 563 "zidl_l.h"
yy68:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy48;
	default:	goto yy69;
	}
yy69:
#line 57 "zidl.l"
	{ return DEF; }
#line 636 "zidl_l.h"
yy70:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy71;
	default:	goto yy49;
	}
yy71:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy48;
	default:	goto yy72;
	}
yy72:
#line 55 "zidl.l"
	{ return OUT; }
#line 715 "zidl_l.h"
yy73:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy77;
	default:	goto yy49;
	}
yy74:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy75;
	default:	goto yy49;
	}
yy75:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy48;
	default:	goto yy76;
	}
yy76:
#line 59 "zidl.l"
	{ return FOR; }
#line 800 "zidl_l.h"
yy77:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy78;
	default:	goto yy49;
	}
yy78:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy79;
	default:	goto yy49;
	}
yy79:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy48;
	default:	goto yy80;
	}
yy80:
#line 51 "zidl.l"
	{ return FLOAT; }
#line 885 "zidl_l.h"
yy81:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy87;
	default:	goto yy49;
	}
yy82:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy83;
	default:	goto yy49;
	}
yy83:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy84;
	default:	goto yy49;
	}
yy84:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy85;
	default:	goto yy49;
	}
yy85:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy48;
	default:	goto yy86;
	}
yy86:
#line 50 "zidl.l"
	{ return PVOID; }
#line 982 "zidl_l.h"
yy87:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'f':	goto yy88;
	default:	goto yy49;
	}
yy88:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy48;
	default:	goto yy89;
	}
yy89:
#line 56 "zidl.l"
	{ return PDEF; }
#line 1061 "zidl_l.h"
yy90:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy95;
	default:	goto yy49;
	}
yy91:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy92;
	default:	goto yy49;
	}
yy92:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy93;
	default:	goto yy49;
	}
yy93:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy48;
	default:	goto yy94;
	}
yy94:
#line 49 "zidl.l"
	{ return BOOL; }
#line 1152 "zidl_l.h"
yy95:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy48;
	default:	goto yy96;
	}
yy96:
#line 45 "zidl.l"
	{ return BIT; }
#line 1225 "zidl_l.h"
yy97:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy109;
	default:	goto yy49;
	}
yy98:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy100;
	case 'r':	goto yy99;
	default:	goto yy49;
	}
yy99:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy105;
	default:	goto yy49;
	}
yy100:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy101;
	default:	goto yy49;
	}
yy101:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy102;
	default:	goto yy49;
	}
yy102:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy103;
	default:	goto yy49;
	}
yy103:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy48;
	default:	goto yy104;
	}
yy104:
#line 61 "zidl.l"
	{ return STATIC; }
#line 1335 "zidl_l.h"
yy105:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy106;
	default:	goto yy49;
	}
yy106:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy107;
	default:	goto yy49;
	}
yy107:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy48;
	default:	goto yy108;
	}
yy108:
#line 52 "zidl.l"
	{ return STRING; }
#line 1420 "zidl_l.h"
yy109:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy48;
	default:	goto yy110;
	}
yy110:
#line 44 "zidl.l"
	{ return SET; }
#line 1493 "zidl_l.h"
yy111:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy112;
	default:	goto yy49;
	}
yy112:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'b':	goto yy113;
	default:	goto yy49;
	}
yy113:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy114;
	default:	goto yy49;
	}
yy114:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy115;
	default:	goto yy49;
	}
yy115:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy48;
	default:	goto yy116;
	}
yy116:
#line 42 "zidl.l"
	{ return MEMBER; }
#line 1590 "zidl_l.h"
yy117:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy123;
	default:	goto yy49;
	}
yy118:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy119;
	default:	goto yy49;
	}
yy119:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy120;
	default:	goto yy49;
	}
yy120:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy121;
	default:	goto yy49;
	}
yy121:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy48;
	default:	goto yy122;
	}
yy122:
#line 41 "zidl.l"
	{ return UNION; }
#line 1687 "zidl_l.h"
yy123:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy124;
	default:	goto yy49;
	}
yy124:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy48;
	default:	goto yy125;
	}
yy125:
#line 48 "zidl.l"
	{ return UINT; }
#line 1766 "zidl_l.h"
yy126:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy127;
	default:	goto yy49;
	}
yy127:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy128;
	default:	goto yy49;
	}
yy128:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy48;
	default:	goto yy129;
	}
yy129:
#line 39 "zidl.l"
	{ return ENUM; }
#line 1851 "zidl_l.h"
yy130:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy144;
	default:	goto yy49;
	}
yy131:
	yych = *++YYCURSOR;
	switch (yych) {
	case '_':	goto yy133;
	case 'r':	goto yy132;
	default:	goto yy49;
	}
yy132:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy141;
	default:	goto yy49;
	}
yy133:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy134;
	default:	goto yy49;
	}
yy134:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'y':	goto yy135;
	default:	goto yy49;
	}
yy135:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy136;
	default:	goto yy49;
	}
yy136:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'h':	goto yy137;
	default:	goto yy49;
	}
yy137:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy138;
	default:	goto yy49;
	}
yy138:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy139;
	default:	goto yy49;
	}
yy139:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy48;
	default:	goto yy140;
	}
yy140:
#line 62 "zidl.l"
	{ return NO_PYTHON; }
#line 1979 "zidl_l.h"
yy141:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'f':	goto yy142;
	default:	goto yy49;
	}
yy142:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy48;
	default:	goto yy143;
	}
yy143:
#line 43 "zidl.l"
	{ return NOREF; }
#line 2058 "zidl_l.h"
yy144:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy145;
	default:	goto yy49;
	}
yy145:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy146;
	default:	goto yy49;
	}
yy146:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy147;
	default:	goto yy49;
	}
yy147:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy148;
	default:	goto yy49;
	}
yy148:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy149;
	default:	goto yy49;
	}
yy149:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy150;
	default:	goto yy49;
	}
yy150:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy48;
	default:	goto yy151;
	}
yy151:
#line 37 "zidl.l"
	{ return NAMESPACE; }
#line 2167 "zidl_l.h"
yy152:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy171;
	default:	goto yy49;
	}
yy153:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy48;
	case 'c':	goto yy163;
	case 't':	goto yy164;
	default:	goto yy154;
	}
yy154:
#line 60 "zidl.l"
	{ return IN; }
#line 2246 "zidl_l.h"
yy155:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy156;
	default:	goto yy49;
	}
yy156:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy157;
	default:	goto yy49;
	}
yy157:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy158;
	default:	goto yy49;
	}
yy158:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy159;
	default:	goto yy49;
	}
yy159:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy160;
	default:	goto yy49;
	}
yy160:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy161;
	default:	goto yy49;
	}
yy161:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy48;
	default:	goto yy162;
	}
yy162:
#line 58 "zidl.l"
	{ return ITERATOR; }
#line 2355 "zidl_l.h"
yy163:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy166;
	default:	goto yy49;
	}
yy164:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy48;
	default:	goto yy165;
	}
yy165:
#line 47 "zidl.l"
	{ return INT; }
#line 2434 "zidl_l.h"
yy166:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy167;
	default:	goto yy49;
	}
yy167:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy168;
	default:	goto yy49;
	}
yy168:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy169;
	default:	goto yy49;
	}
yy169:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy48;
	default:	goto yy170;
	}
yy170:
#line 36 "zidl.l"
	{ return INCLUDE; }
#line 2525 "zidl_l.h"
yy171:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy172;
	default:	goto yy49;
	}
yy172:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy173;
	default:	goto yy49;
	}
yy173:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy174;
	default:	goto yy49;
	}
yy174:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy48;
	default:	goto yy175;
	}
yy175:
#line 38 "zidl.l"
	{ return IMPORT; }
#line 2616 "zidl_l.h"
yy176:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy183;
	case 'e':	goto yy182;
	default:	goto yy49;
	}
yy177:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy178;
	default:	goto yy49;
	}
yy178:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy179;
	default:	goto yy49;
	}
yy179:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy180;
	default:	goto yy49;
	}
yy180:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy48;
	default:	goto yy181;
	}
yy181:
#line 40 "zidl.l"
	{ return CLASS; }
#line 2714 "zidl_l.h"
yy182:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy186;
	default:	goto yy49;
	}
yy183:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy184;
	default:	goto yy49;
	}
yy184:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy48;
	default:	goto yy185;
	}
yy185:
#line 53 "zidl.l"
	{ return CHAR; }
#line 2799 "zidl_l.h"
yy186:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy187;
	default:	goto yy49;
	}
yy187:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy188;
	default:	goto yy49;
	}
yy188:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy189;
	default:	goto yy49;
	}
yy189:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy48;
	default:	goto yy190;
	}
yy190:
#line 35 "zidl.l"
	{ return CHEADER; }
#line 2890 "zidl_l.h"
}
#line 87 "zidl.l"



indent:
	s->token = s->cursor();


#line 2900 "zidl_l.h"
{
	YYCTYPE yych;
	unsigned int yyaccept = 0;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *(YYMARKER = YYCURSOR);
	switch (yych) {
	case 0x00:	goto yy203;
	case '\t':
	case ' ':	goto yy194;
	case '\n':	goto yy200;
	case '\r':	goto yy202;
	case '#':	goto yy197;
	default:	goto yy193;
	}
yy193:
#line 140 "zidl.l"
	{
		if (s->indentstack.top() > 0) {
			s->indentstack.pop();
			s->cursor() = s->token; // retry this token until we have matching indent depths
			return DEDENT;
		}
		goto ignoretoken;
	}
#line 2925 "zidl_l.h"
yy194:
	yyaccept = 1;
	YYMARKER = ++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case ' ':	goto yy194;
	case '\n':	goto yy208;
	case '\r':	goto yy210;
	case '#':	goto yy211;
	default:	goto yy196;
	}
yy196:
#line 119 "zidl.l"
	{
		depth = s->get_token_length();
		if (depth > s->indentstack.top()) {
			s->indentstack.push(depth);
			return INDENT;
		}
		if (depth < s->indentstack.top()) {
			s->cursor() = s->token; // retry this token until we have matching indent depths
			s->indentstack.pop();
			return DEDENT;
		}
		goto ignoretoken;
	}
#line 2954 "zidl_l.h"
yy197:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy199;
	case '\n':	goto yy205;
	case '\r':	goto yy207;
	default:	goto yy197;
	}
yy199:
	YYCURSOR = YYMARKER;
	switch (yyaccept) {
	case 0: 	goto yy193;
	case 1: 	goto yy196;
	}
yy200:
	++YYCURSOR;
#line 113 "zidl.l"
	{
	s->bufferline = s->cursor();
	s->linecounter++;
	goto indent;
}
#line 2979 "zidl_l.h"
yy202:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy200;
	default:	goto yy199;
	}
yy203:
	++YYCURSOR;
#line 132 "zidl.l"
	{
		if (s->indentstack.top() > 0) {
			s->indentstack.pop();
			s->cursor() = s->token; // retry this token until we have matching indent depths
			return DEDENT;
		}
		return 0;
	}
#line 2997 "zidl_l.h"
yy205:
	++YYCURSOR;
#line 101 "zidl.l"
	{
	s->bufferline = s->cursor();
	s->linecounter++;
	goto indent;
}
#line 3006 "zidl_l.h"
yy207:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy205;
	default:	goto yy199;
	}
yy208:
	++YYCURSOR;
#line 107 "zidl.l"
	{
	s->bufferline = s->cursor();
	s->linecounter++;
	goto indent;
}
#line 3021 "zidl_l.h"
yy210:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy208;
	default:	goto yy199;
	}
yy211:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy199;
	case '\n':	goto yy213;
	case '\r':	goto yy215;
	default:	goto yy211;
	}
yy213:
	++YYCURSOR;
#line 95 "zidl.l"
	{
	s->bufferline = s->cursor();
	s->linecounter++;
	goto indent;
}
#line 3046 "zidl_l.h"
yy215:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '\n':	goto yy213;
	default:	goto yy199;
	}
}
#line 148 "zidl.l"

}