/* Generated by re2c 1.0.3 on Sun Dec 24 13:23:19 2017 */
#line 1 "zidl.l"
/*

	ZIDL lexer for re2c lexer generator

*/

#define YYCTYPE char
#define YYCURSOR s->cursor()
#define YYLIMIT s->limit()
#define YYMARKER q
#define YYFILL(n) s->fill(n)

int scan(scanner* s) {
	int depth;
	char* q;

	if (s->bufferline == s->cursor()) goto indent;

ignoretoken:
	s->token = s->cursor();


#line 26 "zidl_l.h"
{
	YYCTYPE yych;
	unsigned int yyaccept = 0;
	if ((YYLIMIT - YYCURSOR) < 10) YYFILL(10);
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy2;
	case '\t':
	case ' ':	goto yy6;
	case '\n':	goto yy9;
	case '\r':	goto yy11;
	case '"':	goto yy12;
	case '#':	goto yy13;
	case '(':	goto yy16;
	case ')':	goto yy18;
	case ',':	goto yy20;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy22;
	case ':':	goto yy25;
	case '=':	goto yy27;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'g':
	case 'h':
	case 'j':
	case 'k':
	case 'l':
	case 'q':
	case 'r':
	case 't':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy29;
	case '[':	goto yy32;
	case ']':	goto yy34;
	case 'b':	goto yy36;
	case 'c':	goto yy37;
	case 'd':	goto yy38;
	case 'e':	goto yy39;
	case 'f':	goto yy40;
	case 'i':	goto yy41;
	case 'm':	goto yy42;
	case 'n':	goto yy43;
	case 'o':	goto yy44;
	case 'p':	goto yy45;
	case 's':	goto yy46;
	case 'u':	goto yy47;
	default:	goto yy4;
	}
yy2:
	++YYCURSOR;
#line 84 "zidl.l"
	{ goto indent; }
#line 116 "zidl_l.h"
yy4:
	++YYCURSOR;
yy5:
#line 85 "zidl.l"
	{ return -1; }
#line 122 "zidl_l.h"
yy6:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case ' ':	goto yy6;
	default:	goto yy8;
	}
yy8:
#line 82 "zidl.l"
	{ goto ignoretoken; }
#line 135 "zidl_l.h"
yy9:
	++YYCURSOR;
#line 73 "zidl.l"
	{ 
	s->bufferline = s->cursor(); 
	s->linecounter++;
	if (s->linetokens == 0) 
		goto indent;
	s->linetokens = 0; 
	return LINEBREAK; 
}
#line 147 "zidl_l.h"
yy11:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy9;
	default:	goto yy5;
	}
yy12:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 0x00:
	case '\n':	goto yy5;
	default:	goto yy49;
	}
yy13:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:
	case '\n':
	case '\r':	goto yy15;
	default:	goto yy13;
	}
yy15:
#line 83 "zidl.l"
	{ goto ignoretoken; }
#line 175 "zidl_l.h"
yy16:
	++YYCURSOR;
#line 65 "zidl.l"
	{ return OPENPAREN; }
#line 180 "zidl_l.h"
yy18:
	++YYCURSOR;
#line 66 "zidl.l"
	{ return CLOSEPAREN; }
#line 185 "zidl_l.h"
yy20:
	++YYCURSOR;
#line 69 "zidl.l"
	{ return COMMA; }
#line 190 "zidl_l.h"
yy22:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy22;
	default:	goto yy24;
	}
yy24:
#line 72 "zidl.l"
	{ return DIGITS; }
#line 211 "zidl_l.h"
yy25:
	++YYCURSOR;
#line 64 "zidl.l"
	{ return COLON; }
#line 216 "zidl_l.h"
yy27:
	++YYCURSOR;
#line 70 "zidl.l"
	{ return EQ; }
#line 221 "zidl_l.h"
yy29:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy30:
	switch (yych) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy29;
	default:	goto yy31;
	}
yy31:
#line 81 "zidl.l"
	{ return IDENTIFIER; }
#line 297 "zidl_l.h"
yy32:
	++YYCURSOR;
#line 67 "zidl.l"
	{ return OPENSQRPAREN; }
#line 302 "zidl_l.h"
yy34:
	++YYCURSOR;
#line 68 "zidl.l"
	{ return CLOSESQRPAREN; }
#line 307 "zidl_l.h"
yy36:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy55;
	case 'o':	goto yy56;
	default:	goto yy30;
	}
yy37:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'h':	goto yy57;
	case 'l':	goto yy58;
	default:	goto yy30;
	}
yy38:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy59;
	case 'l':	goto yy60;
	default:	goto yy30;
	}
yy39:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy61;
	default:	goto yy30;
	}
yy40:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy62;
	case 'o':	goto yy63;
	default:	goto yy30;
	}
yy41:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy64;
	case 'n':	goto yy65;
	case 't':	goto yy67;
	default:	goto yy30;
	}
yy42:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy68;
	default:	goto yy30;
	}
yy43:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy69;
	case 'o':	goto yy70;
	default:	goto yy30;
	}
yy44:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy71;
	default:	goto yy30;
	}
yy45:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy72;
	case 'v':	goto yy73;
	default:	goto yy30;
	}
yy46:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy74;
	case 't':	goto yy75;
	default:	goto yy30;
	}
yy47:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy76;
	case 'n':	goto yy77;
	default:	goto yy30;
	}
yy48:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy49:
	switch (yych) {
	case 0x00:
	case '\n':	goto yy50;
	case '"':	goto yy51;
	case '\\':	goto yy53;
	default:	goto yy48;
	}
yy50:
	YYCURSOR = YYMARKER;
	if (yyaccept == 0) {
		goto yy5;
	} else {
		goto yy52;
	}
yy51:
	++YYCURSOR;
yy52:
#line 71 "zidl.l"
	{ return DQSTR; }
#line 414 "zidl_l.h"
yy53:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:
	case '\n':	goto yy50;
	case '"':	goto yy78;
	case '\\':	goto yy53;
	default:	goto yy48;
	}
yy55:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy79;
	default:	goto yy30;
	}
yy56:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy81;
	default:	goto yy30;
	}
yy57:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy82;
	case 'e':	goto yy83;
	default:	goto yy30;
	}
yy58:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy84;
	default:	goto yy30;
	}
yy59:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'f':	goto yy85;
	default:	goto yy30;
	}
yy60:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy87;
	default:	goto yy30;
	}
yy61:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy88;
	default:	goto yy30;
	}
yy62:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy89;
	default:	goto yy30;
	}
yy63:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy90;
	default:	goto yy30;
	}
yy64:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy92;
	default:	goto yy30;
	}
yy65:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy29;
	case 'c':	goto yy93;
	case 't':	goto yy94;
	default:	goto yy66;
	}
yy66:
#line 60 "zidl.l"
	{ return IN; }
#line 559 "zidl_l.h"
yy67:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy96;
	default:	goto yy30;
	}
yy68:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy97;
	default:	goto yy30;
	}
yy69:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy98;
	default:	goto yy30;
	}
yy70:
	yych = *++YYCURSOR;
	switch (yych) {
	case '_':	goto yy99;
	case 'r':	goto yy100;
	default:	goto yy30;
	}
yy71:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy101;
	default:	goto yy30;
	}
yy72:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy103;
	default:	goto yy30;
	}
yy73:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy104;
	default:	goto yy30;
	}
yy74:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy105;
	default:	goto yy30;
	}
yy75:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy107;
	case 'r':	goto yy108;
	default:	goto yy30;
	}
yy76:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy109;
	default:	goto yy30;
	}
yy77:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy110;
	default:	goto yy30;
	}
yy78:
	yyaccept = 1;
	YYMARKER = ++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:
	case '\n':	goto yy52;
	case '"':	goto yy51;
	case '\\':	goto yy53;
	default:	goto yy48;
	}
yy79:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy29;
	default:	goto yy80;
	}
yy80:
#line 45 "zidl.l"
	{ return BIT; }
#line 712 "zidl_l.h"
yy81:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy111;
	default:	goto yy30;
	}
yy82:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy113;
	default:	goto yy30;
	}
yy83:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy115;
	default:	goto yy30;
	}
yy84:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy116;
	default:	goto yy30;
	}
yy85:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy29;
	default:	goto yy86;
	}
yy86:
#line 57 "zidl.l"
	{ return DEF; }
#line 809 "zidl_l.h"
yy87:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy117;
	default:	goto yy30;
	}
yy88:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy118;
	default:	goto yy30;
	}
yy89:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy120;
	default:	goto yy30;
	}
yy90:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy29;
	default:	goto yy91;
	}
yy91:
#line 59 "zidl.l"
	{ return FOR; }
#line 900 "zidl_l.h"
yy92:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy121;
	default:	goto yy30;
	}
yy93:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy122;
	default:	goto yy30;
	}
yy94:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy29;
	default:	goto yy95;
	}
yy95:
#line 47 "zidl.l"
	{ return INT; }
#line 985 "zidl_l.h"
yy96:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy123;
	default:	goto yy30;
	}
yy97:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'b':	goto yy124;
	default:	goto yy30;
	}
yy98:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy125;
	default:	goto yy30;
	}
yy99:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy126;
	default:	goto yy30;
	}
yy100:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy127;
	default:	goto yy30;
	}
yy101:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy29;
	default:	goto yy102;
	}
yy102:
#line 55 "zidl.l"
	{ return OUT; }
#line 1088 "zidl_l.h"
yy103:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'f':	goto yy128;
	default:	goto yy30;
	}
yy104:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy130;
	default:	goto yy30;
	}
yy105:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy29;
	default:	goto yy106;
	}
yy106:
#line 44 "zidl.l"
	{ return SET; }
#line 1173 "zidl_l.h"
yy107:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy131;
	default:	goto yy30;
	}
yy108:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy132;
	default:	goto yy30;
	}
yy109:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy133;
	default:	goto yy30;
	}
yy110:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy135;
	default:	goto yy30;
	}
yy111:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy29;
	default:	goto yy112;
	}
yy112:
#line 49 "zidl.l"
	{ return BOOL; }
#line 1270 "zidl_l.h"
yy113:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy29;
	default:	goto yy114;
	}
yy114:
#line 53 "zidl.l"
	{ return CHAR; }
#line 1343 "zidl_l.h"
yy115:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy136;
	default:	goto yy30;
	}
yy116:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy137;
	default:	goto yy30;
	}
yy117:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy139;
	default:	goto yy30;
	}
yy118:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy29;
	default:	goto yy119;
	}
yy119:
#line 39 "zidl.l"
	{ return ENUM; }
#line 1434 "zidl_l.h"
yy120:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy140;
	default:	goto yy30;
	}
yy121:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy142;
	default:	goto yy30;
	}
yy122:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy143;
	default:	goto yy30;
	}
yy123:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy144;
	default:	goto yy30;
	}
yy124:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy145;
	default:	goto yy30;
	}
yy125:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy146;
	default:	goto yy30;
	}
yy126:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'y':	goto yy147;
	default:	goto yy30;
	}
yy127:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'f':	goto yy148;
	default:	goto yy30;
	}
yy128:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy29;
	default:	goto yy129;
	}
yy129:
#line 56 "zidl.l"
	{ return PDEF; }
#line 1555 "zidl_l.h"
yy130:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy150;
	default:	goto yy30;
	}
yy131:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy152;
	default:	goto yy30;
	}
yy132:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy153;
	default:	goto yy30;
	}
yy133:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy29;
	default:	goto yy134;
	}
yy134:
#line 48 "zidl.l"
	{ return UINT; }
#line 1646 "zidl_l.h"
yy135:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy154;
	default:	goto yy30;
	}
yy136:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy156;
	default:	goto yy30;
	}
yy137:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy29;
	default:	goto yy138;
	}
yy138:
#line 40 "zidl.l"
	{ return CLASS; }
#line 1731 "zidl_l.h"
yy139:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy157;
	default:	goto yy30;
	}
yy140:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy29;
	default:	goto yy141;
	}
yy141:
#line 51 "zidl.l"
	{ return FLOAT; }
#line 1810 "zidl_l.h"
yy142:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy159;
	default:	goto yy30;
	}
yy143:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy161;
	default:	goto yy30;
	}
yy144:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy162;
	default:	goto yy30;
	}
yy145:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy163;
	default:	goto yy30;
	}
yy146:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy165;
	default:	goto yy30;
	}
yy147:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy166;
	default:	goto yy30;
	}
yy148:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy29;
	default:	goto yy149;
	}
yy149:
#line 43 "zidl.l"
	{ return NOREF; }
#line 1919 "zidl_l.h"
yy150:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy29;
	default:	goto yy151;
	}
yy151:
#line 50 "zidl.l"
	{ return PVOID; }
#line 1992 "zidl_l.h"
yy152:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy167;
	default:	goto yy30;
	}
yy153:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy169;
	default:	goto yy30;
	}
yy154:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy29;
	default:	goto yy155;
	}
yy155:
#line 41 "zidl.l"
	{ return UNION; }
#line 2077 "zidl_l.h"
yy156:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy171;
	default:	goto yy30;
	}
yy157:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy29;
	default:	goto yy158;
	}
yy158:
#line 63 "zidl.l"
	{ return DLNAME; }
#line 2156 "zidl_l.h"
yy159:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy29;
	default:	goto yy160;
	}
yy160:
#line 38 "zidl.l"
	{ return IMPORT; }
#line 2229 "zidl_l.h"
yy161:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy173;
	default:	goto yy30;
	}
yy162:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy175;
	default:	goto yy30;
	}
yy163:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy29;
	default:	goto yy164;
	}
yy164:
#line 42 "zidl.l"
	{ return MEMBER; }
#line 2314 "zidl_l.h"
yy165:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy176;
	default:	goto yy30;
	}
yy166:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'h':	goto yy177;
	default:	goto yy30;
	}
yy167:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy29;
	default:	goto yy168;
	}
yy168:
#line 61 "zidl.l"
	{ return STATIC; }
#line 2399 "zidl_l.h"
yy169:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy29;
	default:	goto yy170;
	}
yy170:
#line 52 "zidl.l"
	{ return STRING; }
#line 2472 "zidl_l.h"
yy171:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy29;
	default:	goto yy172;
	}
yy172:
#line 35 "zidl.l"
	{ return CHEADER; }
#line 2545 "zidl_l.h"
yy173:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy29;
	default:	goto yy174;
	}
yy174:
#line 36 "zidl.l"
	{ return INCLUDE; }
#line 2618 "zidl_l.h"
yy175:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy178;
	default:	goto yy30;
	}
yy176:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy180;
	default:	goto yy30;
	}
yy177:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy181;
	default:	goto yy30;
	}
yy178:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy29;
	default:	goto yy179;
	}
yy179:
#line 58 "zidl.l"
	{ return ITERATOR; }
#line 2709 "zidl_l.h"
yy180:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy182;
	default:	goto yy30;
	}
yy181:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy184;
	default:	goto yy30;
	}
yy182:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy29;
	default:	goto yy183;
	}
yy183:
#line 37 "zidl.l"
	{ return NAMESPACE; }
#line 2794 "zidl_l.h"
yy184:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy29;
	default:	goto yy185;
	}
yy185:
#line 62 "zidl.l"
	{ return NO_PYTHON; }
#line 2867 "zidl_l.h"
}
#line 87 "zidl.l"



indent:
	s->token = s->cursor();


#line 2877 "zidl_l.h"
{
	YYCTYPE yych;
	unsigned int yyaccept = 0;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *(YYMARKER = YYCURSOR);
	switch (yych) {
	case 0x00:	goto yy189;
	case '\t':
	case ' ':	goto yy191;
	case '\n':	goto yy194;
	case '\r':	goto yy196;
	case '#':	goto yy198;
	default:	goto yy188;
	}
yy188:
#line 140 "zidl.l"
	{
		if (s->indentstack.top() > 0) {
			s->indentstack.pop();
			s->cursor() = s->token; // retry this token until we have matching indent depths
			return DEDENT;
		}
		goto ignoretoken;
	}
#line 2902 "zidl_l.h"
yy189:
	++YYCURSOR;
#line 132 "zidl.l"
	{
		if (s->indentstack.top() > 0) {
			s->indentstack.pop();
			s->cursor() = s->token; // retry this token until we have matching indent depths
			return DEDENT;
		}
		return 0;
	}
#line 2914 "zidl_l.h"
yy191:
	yyaccept = 1;
	YYMARKER = ++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case ' ':	goto yy191;
	case '\n':	goto yy200;
	case '\r':	goto yy202;
	case '#':	goto yy203;
	default:	goto yy193;
	}
yy193:
#line 119 "zidl.l"
	{
		depth = s->get_token_length();
		if (depth > s->indentstack.top()) {
			s->indentstack.push(depth);
			return INDENT;
		}
		if (depth < s->indentstack.top()) {
			s->cursor() = s->token; // retry this token until we have matching indent depths
			s->indentstack.pop();
			return DEDENT;
		}
		goto ignoretoken;
	}
#line 2943 "zidl_l.h"
yy194:
	++YYCURSOR;
#line 113 "zidl.l"
	{
	s->bufferline = s->cursor();
	s->linecounter++;
	goto indent;
}
#line 2952 "zidl_l.h"
yy196:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy194;
	default:	goto yy197;
	}
yy197:
	YYCURSOR = YYMARKER;
	if (yyaccept == 0) {
		goto yy188;
	} else {
		goto yy193;
	}
yy198:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy197;
	case '\n':	goto yy205;
	case '\r':	goto yy207;
	default:	goto yy198;
	}
yy200:
	++YYCURSOR;
#line 107 "zidl.l"
	{
	s->bufferline = s->cursor();
	s->linecounter++;
	goto indent;
}
#line 2984 "zidl_l.h"
yy202:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy200;
	default:	goto yy197;
	}
yy203:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy197;
	case '\n':	goto yy208;
	case '\r':	goto yy210;
	default:	goto yy203;
	}
yy205:
	++YYCURSOR;
#line 101 "zidl.l"
	{
	s->bufferline = s->cursor();
	s->linecounter++;
	goto indent;
}
#line 3009 "zidl_l.h"
yy207:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy205;
	default:	goto yy197;
	}
yy208:
	++YYCURSOR;
#line 95 "zidl.l"
	{
	s->bufferline = s->cursor();
	s->linecounter++;
	goto indent;
}
#line 3024 "zidl_l.h"
yy210:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy208;
	default:	goto yy197;
	}
}
#line 148 "zidl.l"

}